### ISSUE TITLE
tuigreet content gets overwritten by systemd startup log

### ISSUE THREAD

**Issue by bnjmnt4n** [apognu/tuigreet#17] opened 2021-03-03 08:22 UTC
When trying to use tuigreet as the default session, the content of tuigreet gets overwritten by systemd's startup log. Is there any known workaround for this?

**Comment by ymatsiuk** [comment] 2021-03-06 18:08
Do you use `vt=1` in greetd config? Seems like switching to `vt=7`(any `vt` other than `1` will work 🤔) helped.

**Comment by bnjmnt4n** [comment] 2021-03-08 06:59
@ymatsiuk yep, I've switched over to `vt=2` for now. I'm pretty unfamiliar with the concept of TTYs and VT, and this seems like the solution used by other display managers such as ly which launch TUI-based interfaces.

**Comment by dR3b** [comment] 2021-03-18 13:06
I have the same problem. Changing VT did not fix the problem.

**Comment by aba-weissenberger** [comment] 2021-04-09 06:06
I have the same problem.

**Comment by foxit64** [comment] 2021-04-09 06:29
That doesn't work for me either.

**Comment by devhell** [comment] 2021-06-02 13:05
Yeah, this is also my issue. Changing VT doesn't seem to help either.

**Comment by apognu** [comment] 2021-06-02 14:24
I'm having trouble reproducing this when `greetd` is configured to use `vt=2`. And even then, I really don't see how to prevent another process to write in the terminal, short of clearing the terminal at each frame, which would introduce blinking.

Does anyone know if and how other TUI tools manage that without rewriting the whole screen (like top) or clearing?

**Comment by bnjmnt4n** [comment] 2021-06-05 17:08
It seem like ly users faced this issue as well (https://github.com/nullgemm/ly/issues/79), which caused the author to change the systemd service type from `simple` to `idle`: https://github.com/nullgemm/ly/commit/4ab41f0bb9c137cc9b7c47b772f14503e87c209b.

Here's the systemd man page on idle:

               Behavior of idle is very similar to simple; however,
               actual execution of the service program is delayed until
               all active jobs are dispatched. This may be used to avoid
               interleaving of output of shell services with the status
               output on the console. Note that this type is useful only
               to improve console output, it is not useful as a general
               unit ordering tool, and the effect of this service type
               is subject to a 5s timeout, after which the service
               program is invoked anyway.

This looks like something that might be useful, especially if switching TTYs doesn't work.

**Comment by apognu** [comment] 2021-06-08 19:25
Can someone confirm @bnjmnt4n's solution (which is outside `tuigreet`'s scope)?

I do not have any other lead as far as a "fix" in `tuigreet` is concerned. I am considering closing this issue as _wontfix_ unless someone can bring something new to the table.

However, it this solution works for people, I will add it to the `README` as a suggested override to `greetd` unit file.

**Comment by jwoudenberg** [comment] 2021-06-08 20:35
I've tried the `simple` to `idle` solution and it works great so far!

**Comment by dR3b** [comment] 2021-06-09 17:52
Unfortunately, this does not work for me. As a result tuigreet starts later. Otherwise the same behavior.

**Comment by apognu** [comment] 2021-06-09 19:55
@dR3b Thanks you for reporting you're still experiencing this, so this is not an actual solution to the issue. It might prevent early messages from being interleaved into `tuigreet`, but subsequent console output would still pose problems.

I still can't think of a solution on this software's side, short of configuring `systemd` _not_ to write to all virtual consoles.

**Comment by apognu** [comment] 2021-06-14 09:32
I'll close this as I don't think this is something `tuigreet` can have any impact on. If I am wrong and someone has an idea, you can still respond and I'll consider reopen it if it pans out.

**Closed by apognu** 2021-06-14 09:32 UTC
Labels: documentation

**Comment by jokeyrhyme** [comment] 2021-08-16 03:39
I reported this in the greetd issue tracker: https://todo.sr.ht/~kennylevinsen/greetd/26

I have found a solution that works for me:

`systemctl edit greetd.service`

```
[Unit]
After=multi-user.target

[Service]
Type=idle
```

**Comment by dR3b** [comment] 2021-08-16 06:25
Works! Thanks!

**Comment by kennylevinsen** [comment] 2021-09-02 21:16
Alternatively:
1. Set greetd to run on something other than tty1, which is often the kernel console and where init log messages go
2. Change the kernel console to be a different tty, freeing up tty1

The idle trick avoid *most* messages, but will not stop future messages from being printed over a textual greeter (good old getty can also get trashed by these).

(Also wrote this over on the greetd tracker)

**Comment by fedoranvar** [comment] 2021-09-25 19:41
For NixOS users: (but then i can't switch TTYs)
```nix
  systemd.services.greetd = {
    unitConfig = {
         After = lib.mkOverride 0 [ "multi-user.target" ];
    };
    serviceConfig = {
      Type = "idle";
    };
  };
```

**Comment by devhell** [comment] 2021-09-26 10:47
> 
> 
> For NixOS users: (but with that overriding i can't switch TTYs)
> 
> ```nix
>   systemd.services.greetd = {
>     unitConfig = {
>          After = lib.mkOverride 0 [ "multi-user.target" ];
>     };
>     serviceConfig = {
>       Type = "idle";
>     };
>   };
> ```

Thanks for that! Maybe you could suggest that as an enhancement to the `greetd` module in NixOS?

**Comment by rambip** [comment] 2021-10-17 07:14
> For NixOS users: (but with that overriding i can't switch TTYs)
> 
> ```nix
>   systemd.services.greetd = {
>     unitConfig = {
>          After = lib.mkOverride 0 [ "multi-user.target" ];
>     };
>     serviceConfig = {
>       Type = "idle";
>     };
>   };
> ```

If it still doesn't work like for me, you can just disable kernel loging:

```nix
boot.kernelParams = ["quiet"];
```

That way you will not get systemd logging at all.

**Comment by niggowai** [comment] 2024-10-07 15:26
The options above for nixos didnt work for me.
I found a solution which works for me on a [Reddit Post](https://www.reddit.com/r/NixOS/comments/vwgk5m/adjust_systemdboot_log_level/)
```nix
{
  boot.consoleLogLevel = 0;
}
```

**Comment by AravindIM** [comment] 2024-11-20 16:50
For me the one that solved my issue is creating a file _/etc/sysctl.d/99-printk.conf_ with the following content:
`kernel.printk=3 4 1 3`

It worked after a reboot

OS: Debian GNU/Linux trixie/sid (Debian Unstable)

I hope it helps!
