### ISSUE TITLE
tuigreet doesn't start sessions with output and error "&>" redirection in their cmdline

### ISSUE THREAD

**Issue by hossamdash** [apognu/tuigreet#55] opened 2022-02-07 14:56 UTC
![image](https://user-images.githubusercontent.com/61992392/152811614-d69c2e66-8565-4e03-be33-be9354a810f2.png)

tuigreet can start the first two files but not the third one, I tried separating the redirection logic into a seprate shell script and having the desktop file just launch the script with the same outcome: being set back to the login screen.

**Comment by apognu** [comment] 2022-02-07 18:44
`tuigreet` does not start any command itself, it instructs `greetd` to start it through its IPC. And as I understand it, those commands are not run in a shell, so I have trouble seeing how file descriptor redirections would apply here.

I can check what I'm sending to `greetd` when I get to a computer, but I am not hopeful.

Using a script should be working, though. Can you share the content of the scripts you are using?

**Comment by hossamdash** [comment] 2022-02-08 07:09
okay i tried again with a script and it seems to work; it used to not work but that was a month ago. either I was doing something wrong or the new version fixed it. I still think it's a good idea to check what is being sent to greetd and maybe open an issue there if needed.
![2022-02-08T09:03:39,095619854+02:00](https://user-images.githubusercontent.com/61992392/152935654-5b22b2e1-224a-4705-8f04-e7cfa6a6bd2d.png)

**Comment by apognu** [comment] 2022-02-09 08:30
I tried your exact third example (the one that does not let you log in) and it works properly on my side, I even tried redirecting `sway`'s output into a file to check if the redirection was working and had no issue with it. So at first sight, it appears `tuigreet` does pass all your parameters to `greetd`.

What exactly is happening when you try opening a session using that file?

**Comment by apognu** [comment] 2022-02-17 05:56
I'll close this, since from my testing, `tuigreet` sends the proper command (with the redirection) to `greetd` and I cannot reproduce the described issue.

Please comment again if you have more information on how I could reproduce this or how `tuigreet` is at fault in the behavior you're seeing.

**Closed by apognu** 2022-02-17 05:56 UTC

**Comment by hossamdash** [comment] 2022-02-26 10:29
we are talking about this right?
![image](https://user-images.githubusercontent.com/61992392/155839797-9afee961-bef6-4dab-b542-f05f50e2e336.png)

> What exactly is happening when you try opening a session using that file?

a blank  screen flashes then i'm sent back to tuigreet
