### ISSUE TITLE
showing further console output

### ISSUE THREAD

**Issue by aserowy** [apognu/tuigreet#45] opened 2021-11-03 06:58 UTC
Heho,

im running tuigreet with nixos. After greetd triggers some services are initialized. The output is rendered over tuigreet.

![IMG20211103070952](https://user-images.githubusercontent.com/8199164/140019761-0660069f-ea8f-45dc-8ae9-928698740fcb.jpg)

My tuigreet config is

<https://github.com/aserowy/nixos/blob/main/shell/sway/tuigreeter.nix>

Sorry in advance if im stupid :D

Kind regards
Alexander

**Comment by jonseitz** [comment] 2021-11-10 01:21
I think this is a duplicate of #17, and there are a couple of nixos-specific solutions in that thread.

**Comment by aserowy** [comment] 2021-11-10 12:42
thanks for the heads up.

**Closed** 2021-11-11 04:41 UTC
